name: CI

on:
  push:
    branches: [build]

jobs:
  build_wheels:
    name: Build wheels on ubuntu-22.04 (auto64) for cp310
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        env:
          CIBW_BUILD: "cp310-*"
          CIBW_SKIP: "*musllinux*"
          CIBW_ARCHS: auto64
          CIBW_ENVIRONMENT_MACOS: TARGET_ARCH=auto64 MACOSX_DEPLOYMENT_TARGET=10.13
          CIBW_BEFORE_ALL: bash scripts/build_Linux.sh
          CIBW_BEFORE_BUILD: pip install pybind11 numpy
          CIBW_TEST_REQUIRES: pytest pillow glfw
          CIBW_TEST_REQUIRES_MACOS: pytest pillow pyopengl
          CIBW_TEST_COMMAND: python -m pytest {project}/tests
          CIBW_TEST_COMMAND_LINUX: >
            xvfb-run -s "-screen 0 640x480x24" python -m pytest {project}/tests
          CIBW_TEST_SKIP: "*-macosx_arm64"

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-ubuntu-22.04-auto64-cp310
          path: ./wheelhouse/*.whl
